[project]
name = "itapa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "folium>=0.18.0",
    "geopandas>=1.0.1",
    "openpyxl>=3.1.5",
    "seaborn>=0.13.2",
]
